title:        mapix
tagline:      "Python, Douban"
url:          http://mapix.com
author:
  name:       "mapix"
  email:      "luoweifeng1989@gmail.com"
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
encoding:     utf-8


